version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: nikengp/node:node-6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: shellcheck
          command: echo $0 &7 echo $BASH && ps  -ef | grep $$ | grep -v grep
      - run:
          name: test
          command: npm run test:ci
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: reports